ghost_port: "2368"
ghost_url: "http://www.yourdomain.com:2368"
ghost_volume: "/data/wwwroot/ghost/content"


ghost_db_client: mysql
ghost_db_host: "172.17.0.1"
ghost_db_user: root
ghost_db_password: "123456"
ghost_db_database: ghost
